name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: 5de4b3e9d39e1c5f7f2303b0740a0b38
          TIMEZONE: Asia/Seoul
